@server = https://ec3-guillermo-becerra.onrender.com
@api = {{server}}/api/ec3

GET {{api}}

################ Categorias: ################
###
GET {{api}}/categorias
###
POST {{api}}/categorias
Content-Type: application/json

{"nombre": "Instrumentos de Cuerda3"}
################ Instrumentos: ################
###
GET {{api}}/instrumentos
###
POST {{api}}/instrumentos
Content-Type: application/json

{"nombre": "Guitarra4", "categoria": "http://localhost/api/ec3/categorias/2"}
###
GET {{api}}/instrumentos/1/categoria
###
GET {{api}}/instrumentos?sort=nombre,desc